version: "3.8"
services:
  database:
    container_name: pt-len
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pt-len-db
    ports:
      - "5432:5432"
volumes:
  database:
    driver: local
